server {
    # 监听端口，这里选用 8080 避免和现有实验室业务 80 冲突，你可以随时修改
    listen 8080;
    server_name _; 

    # 指向我们上传到服务器的编译后静态资源文件夹
    root /【Target dist filepath】/dist;
    index index.html;

    # 【1】前端 SPA 单页应用核心基建
    # 当你在前端随意切换路由(如 /monitor, /history) 并且刷新时，Nginx必须通过这个回溯至 index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 【2】普通 API 流量脱壳与分发
    # 匹配 /api/ 强行抓回本地(127.0.0.1)的 learner_backend.py 所在的 12353 端口
    location /api/ {
        proxy_pass http://127.0.0.1:12353;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 【3】态势感知大动脉 (WebSocket 通道守护) 
    # Nginx 默认会阻断 HTTP/1.1 Upgrade，必须加上这几行魔法配置
    location /ws/ {
        proxy_pass http://127.0.0.1:12353;
        
        # 激活 WebSocket Upgrade 协议切换特征信号
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # 将 TCP 超时强行延长到 1 个小时，防止 Nginx 因为探针 1 秒 1 次而意外判定空闲切断
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
