[forward]
# 接收端口的 PCI 地址
rx_pci=【【】】
# 发送端口的 PCI 地址
tx_pci=【【】】
# 分发核心数（即收发队列数）
num_cores=【【】】
# 运行时间（秒），填 0 表示一直运行
timeout=0

rl_delay=0

# 目标子机的 MAC 地址，从 mac_0 开始连续编号
mac_0=【【】】
mac_1=【【】】
mac_2=【【】】
mac_3=【【】】
